### ISSUE TITLE
Changes are not reflected, webpack bundle is served instead

### ISSUE THREAD

**Issue by mylk** [tsevdos/greek-in-tech-site#70]
While trying to debug the failling tests on https://github.com/tsevdos/greek-in-tech/pull/69, I realised that the whole project is minified into to _js/dist/0.bundle.js_ and served instead of the actual code when:

```
npm start [test-webserver]
```

I guess that the bundle has to be ignored from the project and generated whenever the server is started.

Thanks in advance

**Comment by tsevdos** [comment]
You need to install `webpack-dev-server` (have a look here http://webpack.github.io/docs/webpack-dev-server.html). When you use the `dev server`, webpack serves the source files so you can still debug with ease (you can do more stuff have a look at the documentation).

Let me know if you are ok with this in order to close the issue.

**Comment by mylk** [comment]
Thanks alot for the help.

I reinstalled `webpack-dev-server` and got the tests passing.
